development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:d54be72445a10a6d993698f4edafa6b1@albacore.redistogo.com:9707/
  channel_prefix: shopping_cart_production
